# Generated by Django 5.1.5 on 2025-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_company_name_project_date_project_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa firmy')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logo (WebP, automatyczna konwersja)')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
